# -*- coding: utf-8 -*-
"""Estimasi Harga Mobil Bekas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lfexa0KKble7JtBTIq88PvSMdT3rYPcu

# Deskripsi library yang digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# Memanggil Dataset"""

df = pd.read_csv('toyota.csv')

"""# Deskripsi Dataset"""

df.head()

df.info()

sns.heatmap(df.isnull())

df.describe()

"""# Jumlah Mobil Berdasarkan Model"""

models = df.groupby('model').count()[['tax']].sort_values(by='tax',ascending=True).reset_index()
models = models.rename(columns={'tax':'numberOfCars'})

fig = plt.figure(figsize=(15,5))
sns.barplot(x=models['model'], y=models['numberOfCars'], color='royalblue')
plt.xticks(rotation=60)

"""# Ukuran Mesin"""

engine = df.groupby('engineSize').count()[['tax']].sort_values(by='tax').reset_index()
engine = engine.rename(columns={'tax':'count'})

plt.figure(figsize=(15,5))
sns.barplot(x=engine['engineSize'], y=engine['count'], color='royalblue')

"""# Distribusi Mileage"""

plt.figure(figsize=(15,5))
sns.distplot(df['mileage'])

"""# Distribusi Harga Mobil"""

plt.figure(figsize=(15,5))
sns.distplot(df['price'])

"""# Seleksi Fitur"""

features = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
x = df[features]
y = df['price']
x.shape, y.shape

"""# Split Data Training dan Data Testing"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=70)
y_test.shape

"""# Membuat Model Regresi Linear"""

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
pred = lr.predict(x_test)

score = lr.score(x_test, y_test)
print('Akurasi Model Regresi Linear =', score)

"""# Membuat Inputan Model Regresi Linear"""

# Year=2019, mileage=5000, tax=145, mpg=30.2, engineSize=2
input_data = np.array([[2019,5000,145,30.2,2]])

prediction = lr.predict(input_data)
print('Estimasi harga mobil dalam EUR :', prediction)

"""# Save Model"""

import pickle

filename = 'estimasi_mobil.sav'
pickle.dump(lr,open(filename,'wb'))